sources:
  - Elastre.glyphs

familyName: Elastre

outputDir: ../fonts
vfDir: $outputDir/variable
otDir: $outputDir/otf
woffDir: $outputDir/webfonts

autohintTTF: true
autohintOTF: false
buildVariable: true
buildStatic: true
buildTTF: false
buildOTF: true

stat:
  "Elastre[MORF,wdth].ttf":
    - name: Width
      tag: wdth
      values:
        - name: Regular
          value: 100
        - name: Expanded
          value: 125
        - name: Extra Expanded
          value: 150
        - name: Ultra Expanded
          value: 200
    - name: Inktrap
      tag: MORF
      values:
        - name: No Inktrap
          value: 0
        - name: Inktrap
          value: 100