sources:
  - Elastre.glyphs

axisOrder:
    - wdth
    - INKT

familyName: Elastre

outputDir: ../fonts

buildStatic: false

stat:
  Elastre[INKT,wdth].ttf:
    - name: Width
      tag: wdth
      values:
        - name: Super
          value: 100
          flags: 2
        - name: Mega
          value: 150
        - name: Ultra
          value: 200
    - name: Ink Trap
      tag: INKT
      values:
        - name: Neutral
          value: 0
          flags: 2
        - name: Expressive
          value: 100