sources:
  - Elastre.glyphs

axisOrder:
    - wdth
    - MORF

familyName: Elastre

outputDir: ../fonts
vfDir: $outputDir/variable
otDir: $outputDir/otf
woffDir: $outputDir/webfonts

autohintTTF: true
autohintOTF: false
buildVariable: true
buildStatic: true
buildTTF: false
buildOTF: true

stat:
  "Elastre[MORF,wdth].ttf":
    - name: Width
      tag: wdth
      values:
        - name: Regular
          value: 100
        - name: Expanded
          value: 125
        - name: Extra Expanded
          value: 150
        - name: Ultra Expanded
          value: 200
    - name: Inktrap
      tag: MORF
      values:
        - name: No Inktrap
          value: 0
        - name: Inktrap
          value: 100

statFormat4:
      - name: Regular
        location:
          wdth: 100
          MORF: 0
      - name: Regular Inktrap
        location:
          wdth: 100
          MORF: 100
      - name: Expanded
        location:
          wdth: 125
          MORF: 0
      - name: Expanded Inktrap
        location:
          wdth: 125
          MORF: 100
      - name: Extra Expanded
        location:
          wdth: 150
          MORF: 0
      - name: Extra Expanded Inktrap
        location:
          wdth: 150
          MORF: 100
      - name: Ultra Expanded
        location:
          wdth: 200
          MORF: 0
      - name: Ultra Expanded Inktrap
        location:
          wdth: 200
          MORF: 100