sources:
  - Elastre.glyphs

axisOrder:
    - HEXP
    - INKT

familyName: Elastre

outputDir: ../fonts

buildStatic: false

stat:
  Elastre[HEXP,INKT].ttf:
    - name: Hyper Expansion
      tag: HEXP
      values:
        - name: Super
          value: 0
        # flags: 2
        - name: Mega
          value: 50
        - name: Ultra
          value: 100
    - name: Inktrap
      tag: INKT
      values:
        - name: Line
          value: 0
        - name: Inktrap
          value: 100